### ISSUE TITLE
Php-errors.log

### ISSUE THREAD

**Issue by TetyaseDaWina** [tomolimo/ticketcleaner#1]
Hi, thank you to make this plugin available with GLPI 0.90

Following our exchange, filter works type 0 and 1 for HTML and Text.
But, there is some problems in the php-errors.log
Here is my log:

2016-06-06 11:05:02 [@supp]
  **\* PHP Notice(8): Undefined index: replace
  Backtrace :
  plugins/ticketcleaner/hook.php:222
  plugins/ticketcleaner/hook.php:310                 PluginTicketCleaner::cleanText()
  :                                                  PluginTicketCleaner::plugin_pre_item_add_ticketcleaner()
  inc/plugin.class.php:1095                          call_user_func()
  inc/commondbtm.class.php:790                       Plugin::doHook()
  inc/mailcollector.class.php:565                    CommonDBTM->add()
  inc/mailcollector.class.php:1598                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:799                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2016-06-06 11:05:02 [@supp]
  **\* PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  plugins/ticketcleaner/hook.php:222
  plugins/ticketcleaner/hook.php:310                 PluginTicketCleaner::cleanText()
  :                                                  PluginTicketCleaner::plugin_pre_item_add_ticketcleaner()
  inc/plugin.class.php:1095                          call_user_func()
  inc/commondbtm.class.php:790                       Plugin::doHook()
  inc/mailcollector.class.php:565                    CommonDBTM->add()
  inc/mailcollector.class.php:1598                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:799                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2016-06-06 11:05:02 [@supp]
  **\* PHP Notice(8): Undefined index: replace_in_title
  Backtrace :
  plugins/ticketcleaner/hook.php:228
  plugins/ticketcleaner/hook.php:310                 PluginTicketCleaner::cleanText()
  :                                                  PluginTicketCleaner::plugin_pre_item_add_ticketcleaner()
  inc/plugin.class.php:1095                          call_user_func()
  inc/commondbtm.class.php:790                       Plugin::doHook()
  inc/mailcollector.class.php:565                    CommonDBTM->add()
  inc/mailcollector.class.php:1598                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:799                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2016-06-06 11:05:02 [@supp]
  **\* PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  plugins/ticketcleaner/hook.php:228
  plugins/ticketcleaner/hook.php:310                 PluginTicketCleaner::cleanText()
  :                                                  PluginTicketCleaner::plugin_pre_item_add_ticketcleaner()
  inc/plugin.class.php:1095                          call_user_func()
  inc/commondbtm.class.php:790                       Plugin::doHook()
  inc/mailcollector.class.php:565                    CommonDBTM->add()
  inc/mailcollector.class.php:1598                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:799                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2016-06-06 11:05:03 [@supp]
  **\* PHP User Notice(1024): Configuration incorrecte du dossier accepted pour le collecteur
Variables:<wddxPacket version='1.0'><header><comment>Variables</comment></header><data><struct><var name='mid'><number>1</number></var><var name='folder'><string>accepted</string></var><var name='name'><string>Archivage ticket</string></var></struct></data></wddxPacket>
  Backtrace :
  :
  inc/mailcollector.class.php:1542                   trigger_error()
  inc/mailcollector.class.php:581                    MailCollector->deleteMails()
  inc/mailcollector.class.php:1598                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:799                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2016-06-06 11:05:07 [@supp]
  **\* PHP Notice(8): Unknown: [TRYCREATE] The requested item could not be found. (errflg=2)
  Backtrace :
  :

**Comment by tomolimo** [comment]
Solved with release 2.0.0
