### ISSUE TITLE
Compatibility with GLPI 9.4

### ISSUE THREAD

**Issue by Anthonyd95** [tomolimo/ticketcleaner#10]
Hi !
Have you planned to make your plug-in compatible with GLPI 9.4 ?
and  if it's the case do you have an idea when you will adapte this plugin to the new glpi version ?

Thanks in advance for your feed-back !

**Comment by tomolimo** [comment]
Hello,
Yes this is planned, but yet we still have a big issue in GLPI 9.2...
So let's fix this and I'll be able to provide the 9.3 and 9.4 release
Thank you,
Regards,
Tomolimo

**Comment by Anthonyd95** [comment]
Hello,
Thank you for your response and your amazing work on this plug in.
Regards,
Anthony
