### ISSUE TITLE
[GLPI 9.4] filter don't work

### ISSUE THREAD

**Issue by juveboss** [tomolimo/ticketcleaner#13]
Hello,

The plugin does not work anymore ... I'm on Gmail and my text filters in the plugin not changed.

Filter : 
/[a-z ]+Attention : .*?de nos services.\./ui

My signature : 
Attention : Le présent message et toutes les pièces jointes sont confidentiels et établis à l'attention exclusive des destinataires indiqués. Toute autre diffusion ou utilisation non autorisée est interdite. Si vous recevez ce message par erreur, nous vous remercions de nous en avertir par e-mail et de détruire le message.
Toutes nos prestations sont accomplies sous couvert des Conditions Générales de Vente  dont un exemplaire est disponible sur notre site Internet ou sur simple demande auprès de nos services.

Thanks for help
GLPI : 9.4.0  / 
Ticket Cleaner : 2.5.1

**Comment by PepeImpulso** [comment]
I'm having the same problem with 9.4.3. 
I would also please need a clear explanation on how to use the plugin.

**Comment by tomolimo** [comment]
Hello @PepeImpulso 
For explanations, please first read the wiki: https://github.com/tomolimo/ticketcleaner/wiki 
And then if you have more questions I'll be happy to answer.

Hello @juveboss 
Could you provide the debug logs like explained in the wiki: https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters

Thank you
Regards,
Tomolimo

**Comment by TBastien** [comment]
Hello,
Thanks for your plugins. I upgrade today to glpi 9.4.4. and plugins 2.5.1
With TXT mail it's work but not with HTML.

html.class.php on glpi 9.4.4 is allready without space but is not exacte the same function.
what are I doing wrong.
Thanks for help


[clean.txt](https://github.com/tomolimo/ticketcleaner/files/3650623/clean.txt)
![Capture](https://user-images.githubusercontent.com/19180435/65571056-00f77900-dfaf-11e9-80eb-1cde0bed59cb.PNG)

**Comment by tomolimo** [comment]
Hello @TBastien 

Could you provide the debug logs like explained in the wiki: https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters

Thank you
Regards,
Tomolimo

PS: do not use existing issue to post your own, but create new one, please! This will prevent confusions.

**Comment by victoria1984** [comment]
Hello,
Thanks for your plugins. I 'm using glpi 9.4.4. and plugins 2.5.1
mail it'isn work with HTML.

html.class.php on glpi 9.4.4 is allready without space but is not exacte the same function.
and i've done this filter:
/(\<p class=MsoNormal style='line-height:80%'\>(.*)\<\/p>)/

The filter is prove with a regular expression program and is correct, but the mails don't replace the expresion.
![filtro](https://user-images.githubusercontent.com/38318643/97340262-d8157780-1883-11eb-9681-6961e70c7ae3.PNG)
Could you help me?

Thanks

**Comment by tomolimo** [comment]
Hello @victoria1984 
Do not use an existing issue to post new issue. Use a new issue for that, otherwise it's impossible to answer all issues when it's in the same thread.
Thank you to open a new issue. and then if necessary, you may refer to current issue.
Thank you,

Apart of that, if you want help from me, I need more info: could you provide the debug information like explained here: https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @TBastien 
I close this issue, as I got no news since last post.
Feel free to reopen, or to open a new issue.
Thank you,
Regards,
Tomolimo
