### ISSUE TITLE
Clean html email glpi 9.4.4

### ISSUE THREAD

**Issue by TBastien** [tomolimo/ticketcleaner#14]
Hello,
Thanks for your plugins. I upgrade today to glpi 9.4.4. and plugins 2.5.1
With TXT mail it's work but not with HTML.

html.class.php on glpi 9.4.4 is allready without space but is not exacte the same function.
what are I doing wrong.
Thanks for help

[clean.txt](https://github.com/tomolimo/ticketcleaner/files/3651729/clean.txt)
[TicketCleaner.log](https://github.com/tomolimo/ticketcleaner/files/3651745/TicketCleaner.log)

**Comment by tomolimo** [comment]
Hello @TBastien,

Thank you, but to help you I also need to have the following:

Could you also post the filters?

- 'Supprime les espaces'
- 'Sofia'

Could you also post initial view of the email, and what is expected after the filters?

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @TBastien 
I close this issue I got no news since last question.
Feel free to reopen if you want to post more info.
Thank you
Regards,
Tomolimo
