### ISSUE TITLE
[2.5.1 GLPI 9.4.4] don't get debug filter trace to log

### ISSUE THREAD

**Issue by Armin83** [tomolimo/ticketcleaner#15]
I try to get trace logs https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters
but i got only this

> 2019-10-04 17:54:02 [@server]
Ticket: 'Test1751'
2019-10-04 18:43:02 [@server]
Ticket: 'Test1777'

No Initial text content: / No After text

**Comment by tomolimo** [comment]
Hello @Armin83 
Could you give the GLPI configuration and plugin configuration?
Thank you
Regards,
Tomolimo

**Comment by Armin83** [comment]
The filter we try to use:
/xx yy GmbH..xx-yyy-Straße 1..12345 xx .*?Besuchen Sie uns im Web unter www\.xxxyyy\.de..../us

[code]
 GLPI 9.4.4 (/glpi => /var/www/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux inventar01 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:41 UTC 2016 i686
PHP 7.0.33-0ubuntu0.16.04.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="4M" 
Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at ticketyy.xx Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.24-0ubuntu0.16.04.1
	Server SQL Mode: 
	Parameters: glpidbuser@localhost/glpidb
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (5.7.24) - Perfect!Database version seems correct (5.7.24) - Perfect!
OK/var/www/glpi/files/_log : OK
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_cache : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src)
phpCas version 1.3.3 in (/usr/share/php)

LDAP directories
 
Server: 'yy03.xx.com', Port: '389', BaseDN: 'dc=xx, dc=com', Connection filter:
		'(&(!(cn=SystemMail*))(!(cn=*test*))(!(cn=*admin*))(!(cn=admin*))(!(cn=*Admin))(!(cn=HealthMailbox*))(objectCategory=person)(mailnickname=*)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
		)', RootDN: 'cn=IT-yy, cn=Users, dc=xx, dc= de', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@smtprelay.xx.de)

Mails receivers
 
Name: 'it-support@yy.de' Active: Yes
	Server: '{xxx.yy.de:993/imap/ssl/novalidate-cert}' Login: 'xx@yyy.de' Password: Yes

Plugins list
 
	actualtime           Name: ActualTime                     Version: 1.2.0      State: Enabled
	news                 Name: Alarme                         Version: 1.5.4      State: Enabled
	reports              Name: Berichte                       Version: 1.13.1     State: Not activated
	branding             Name: Branding                       Version: 1.0.2      State: Enabled
	collaborativetools   Name: Collaborative tools            Version: 1.0.1      State: Enabled
	dashboard            Name: Dashboard                      Version: 0.9.8      State: Enabled
	datainjection        Name: File injection                 Version: 2.7.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.8.5      State: Enabled
	holiday              Name: Holidays                       Version: 0.1        State: Enabled
	addressing           Name: IP Adressierung                Version: 2.8.0      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.1      State: Enabled
	mreporting           Name: More Reporting                 Version: 1.6.1      State: Enabled
	mydashboard          Name: My Dashboard                   Version: 1.7.4      State: Enabled
	pdf                  Name: PDF-Ausgabe                    Version: 1.6.0      State: Enabled
	ticketcleaner        Name: Ticket Cleaner                 Version: 2.5.1      State: Enabled
	behaviors            Name: Verhalten                      Version: 2.2.2      State: Enabled
[/code]

**Comment by tomolimo** [comment]
Thank you,
Could you also check if there are any error in PHP log files?

**Comment by Armin83** [comment]
Cleaner Log
> 2019-10-07 09:33:02 [@xx]
Ticket: 'Bestellung'
2019-10-07 10:00:01 [@xx]
Ticket: 'Walzstahlverteiler'

Because of a glpi error in 9.4.4 cron have to run as root and so i have some error logs if i don't change the log files persmission back to www-data.
I changed it now but on friday all was correct and i did not have errors from this plugin

> [2019-10-07 09:53:46] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"6@inventar01"}
[2019-10-07 09:55:58] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"17@inventar01"}
[2019-10-07 09:56:08] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"8@inventar01"}
[2019-10-07 09:58:13] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"428@inventar01"}
[2019-10-07 09:59:11] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"6@inventar01"}
[2019-10-07 10:02:42] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"8@inventar01"}
[2019-10-07 10:03:14] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"428@inventar01"}
[2019-10-07 10:05:30] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"6@inventar01"}
[2019-10-07 10:06:00] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"17@inventar01"}
[2019-10-07 10:07:47] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"8@inventar01"}
[2019-10-07 10:08:14] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"428@inventar01"}
[2019-10-07 10:09:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/mail.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/notificationmailing.class.php:168              Toolbox::logInFile()
  inc/notification.class.php:484                     NotificationMailing->sendNotification()
  inc/notificationeventabstract.class.php:124        Notification::send()
  inc/notificationevent.class.php:163                NotificationEventAbstract::raise()
  inc/ticket.class.php:1636                          NotificationEvent::raiseEvent()
  inc/commondbtm.class.php:1475                      Ticket->post_updateItem()
  inc/itilsolution.class.php:358                     CommonDBTM->update()
  inc/commondbtm.class.php:1142                      ITILSolution->post_addItem()
  front/itilsolution.form.php:57                     CommonDBTM->add()
  {"user":"8@inventar01"}
[2019-10-07 10:11:00] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"17@inventar01"}
[2019-10-07 10:14:38] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"8@inventar01"}
[2019-10-07 10:16:01] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"17@inventar01"}
[2019-10-07 10:18:16] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"428@inventar01"}
[2019-10-07 10:22:59] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"17@inventar01"}
[2019-10-07 10:23:17] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"428@inventar01"}
[2019-10-07 10:24:39] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"8@inventar01"}
[2019-10-07 10:27:59] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"17@inventar01"}
[2019-10-07 10:28:18] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"428@inventar01"}
[2019-10-07 10:29:09] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"6@inventar01"}
[2019-10-07 10:29:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"8@inventar01"}
[2019-10-07 10:33:19] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"428@inventar01"}
[2019-10-07 10:34:41] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"8@inventar01"}
[2019-10-07 10:34:54] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"17@inventar01"}
[2019-10-07 10:38:20] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"428@inventar01"}
[2019-10-07 10:39:42] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"8@inventar01"}
[2019-10-07 10:40:07] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:587                          error_log()
  inc/crontask.class.php:858                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"17@inventar01"}

**Comment by tomolimo** [comment]
Thank you
Could you confirm that you were running in debug?
Could you also confirm that you have the TicketCleaner.log file in the log/ folder?

**Comment by tomolimo** [comment]
I think I found why you don't have any info in the log:
the GLPI debug mode is only active for super-admin users, and of course it is not active with the cron...
Are you trying to integrate emails? If yes, you may run the mailgate manually from the 'automatic actions', and such the debug mode will be active (if enable in your super-admin profile).

**Comment by Armin83** [comment]
That's it. Thanks
Sorry i did not know that i have to run import manual to get the debug mode active in this case. Now i have the necessary input in the debug log to find the correct filter.

I have change my filter to html :( ... much work for me ;)

**Comment by tomolimo** [comment]
you're welcome, I'll change the Wiki to indicate this. Thank you
