### ISSUE TITLE
Images with links.

### ISSUE THREAD

**Issue by MCGS94** [tomolimo/ticketcleaner#17]
Hi,

I'm sorry if i post this on the wrong section but i'm on a dead end because i have no knowledge about PHP. Can you please tell me how can i remove images with links like:

 <a href="https://www.qries.com/">
         <img alt="Qries" src="https://www.qries.com/images/banner_logo.png"
         width=150" height="70">
  </a>

` <a href="https://www.qries.com/">
         <img alt="Qries" src="https://www.qries.com/images/banner_logo.png"
         width=150" height="70">
      </a>`
Thank you very much.

**Comment by tomolimo** [comment]
Hello @MCGS94 
You may add a filter that will look like:
@<a href="https://www\.qries\.com">.*</a>@

You may test this filter like explained here: 
https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters

Regards,
Tomolimo

**Comment by MCGS94** [comment]
Hi,

Thank you for your fast reply! But unfortunately, it doesn't work.

I've tried to remove the images only before. It works great but it leaves a big empty space. Images with links were on that empty space. (see img below)

![tempsnip](https://user-images.githubusercontent.com/38141357/68465267-6f686180-0212-11ea-9239-00e18271b3fc.png)

This is what i've put on the plugin.
![Capture](https://user-images.githubusercontent.com/38141357/68465915-ad19ba00-0213-11ea-8c32-7fc92f3b3daa.PNG)

And it seems like nothing hapenned on the Ticketcleaner.log
[log.txt](https://github.com/tomolimo/ticketcleaner/files/3823900/log.txt)

Can you please help me find a solution to this problem?

Thank you in advance!

**Comment by tomolimo** [comment]
Did you try in debug mode like explained here: https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters#how-to-debug-test-filters

**Comment by MCGS94** [comment]
[debug.txt](https://github.com/tomolimo/ticketcleaner/files/3836251/debug.txt)

Hi
,
Sorry, i didn't follow the instructions thoroughly but here's what the log says.

PS: i've blocked the images through glpi (management > documents > blacklisted for import > yes )

Hope you can help me :)

Thanks in advance !

**Comment by tomolimo** [comment]
Hello @MCGS94,

> PS: i've blocked the images through glpi (management > documents > blacklisted for import > yes )

Beware that this will block all images....

What you have to understand is that Ticket Cleaner plugin has two parts:
1. one for cleaning text
1. and one for preventing import of images (whatever type it can be)

The text cleaning mechanism may be used to clean images too, but it needs to be able to master a little bit the regexp.
The image cleaning mechanism is explained here: https://github.com/tomolimo/ticketcleaner/wiki#image-filters


To explain the result you got: the regex @.*@ with empty replacement will delete al the text of the email: this is what you can see on the line:

> 2019-11-12 14:06:38 [2@srv-glpitest]
>         After filter: mail       text:

But it will not delete the images that probably are in the email attachments... To do that you need to put these images into the folder 'pictures' in the 'ticketcleaner' folder.

Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
Closed this as it is no longer living...
Regards,
Tomolimo
