### ISSUE TITLE
Retrieve the last mail header in ticket tracking / Récupérer le dernier en-tête mail dans suivi du ticket

### ISSUE THREAD

**Issue by ghost** [tomolimo/ticketcleaner#18]
Hello @tomolimo

First of all thank you for the work on the different plugins.

Does the "ticketcleaner" also make it possible to recover the mail header when a person is doing an normal or anonymous follow-up by email (via the collector)?

Thank you

GLPI version 9.4.6

_____________

Bonjour @tomolimo  

Tout d'abord merci pour le travail sur les différents plugins.

Est ce que le "ticketcleaner" permet également de récupérer l'en-tête mail lors qu'une personne réalise un suivi normal/anonyme par mail (via le collecteur) ?

Merci 

GLPI version 9.4.6

**Comment by tomolimo** [comment]
Hello @stdglpi 
Thank you for using the plugin :smiley: 
But could you post your question in English, thank you?
It may help other people
Thank you
Regards,
Tomolimo

**Comment by stdglpi** [comment]
Hello @tomolimo

First of all thank you for the work on the different plugins.

Does the "ticketcleaner" also make it possible to recover the mail header when a person is doing an normal or anonymous follow-up by email (via the collector)?

Thank you

GLPI version 9.4.6

**Comment by tomolimo** [comment]
Hello @stdglpi 
The Ticketcleaner plugin is working on:

### Texts:
1. The ticket title (called "name" in glpi_tickets table in DB), at ticket creation, and also ticket update
1. The ticket description (called "content" in glpi_tickets table in DB), at ticket creation, and also ticket update
1. The followup content at followup creation, and also followup update

### Images:
1. When ticket is created via a mailcollector

Could you explain in details the process you are expecting? What you would like to get from the email header, and when?

Thank you
Regards,
Tomolimo

**Comment by ghost** [comment]
Hello @tomolimo 

Ok I understand.

**Goal :** 

In each followup (taken by mail with the collector) I would like this :

Of : xxxxxx <xxxxx@xxxxx>
Sent : xxxx xxx xxx
To : xxx xxx xxxx
Subject : xxxxx xxxxx

##Followup.description##

currently the collector clean this part in the code.
We are using the anonymous helpdesk and it will help us to see if the requester add some people in the loop.

Unfortunately I think i'm off topic for the possibilities of this plugin.

**Comment by tomolimo** [comment]
Hello @stdglpi 

Yes, exactly, this request is out of scope for this plugin :disappointed: 
This is an interesting feature request, but for another plugin...

Sorry, I'm going to close this issue.

Thank you,
Regards,
Tomolimo
