### ISSUE TITLE
GLPI 9.3 and 9.4 does not work with html

### ISSUE THREAD

**Issue by victoria1984** [tomolimo/ticketcleaner#19]
Hello, 
I create a new issue for my problem.
I'm using this plugin with glpi 9.3.2 and glpi 9.4.4 but when i make a regex for html, this filter don't work.
I've proved the regex with the program named in the wiki and works ok.

In glpi, when i use the expression for txt, works ok, however i need use html expression.
attachment Ticketcleaner.log and my regular expression.

/(\<p class=MsoNormal style='line-height:80%'\>(.*)\<\/p>)/
[TicketCleaner.log](https://github.com/tomolimo/ticketcleaner/files/5456926/TicketCleaner.log)
[TicketCleaner.log](https://github.com/tomolimo/ticketcleaner/files/5456930/TicketCleaner.log)
[TicketCleaner.log](https://github.com/tomolimo/ticketcleaner/files/5456933/TicketCleaner.log)

Thanks.

**Comment by tomolimo** [comment]
Hello @victoria1984 
All these log files have the same content: is it intend?
Did you apply the debug filter procedure like describe here: [Debug-filters](https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters)?
Thank you to provide me the log file like described in the Debug-filter section.
Regards,
Tomolimo

**Comment by victoria1984** [comment]
I'm going to extract the log again and send to you.

Thank's

**Comment by tomolimo** [comment]
Don't forget to switch to Debug mode like explained in the wiki!

**Comment by victoria1984** [comment]
Hi, 
I've activated de debug mode with super-admin profile and i sent an e-mail with the structure that i want remove.
And this is the log that plugin made.
[TicketCleaner.log](https://github.com/tomolimo/ticketcleaner/files/5481029/TicketCleaner.log)

**Comment by tomolimo** [comment]
Hello @victoria1984 
To which email address did you send an email?
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @victoria1984 
I've checked the new log file you sent, but there is no filter debug in it!
Could you do screen copies of the plugin filters in GLPI?
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @victoria1984 
![image](https://user-images.githubusercontent.com/7569958/98101807-0225f580-1e93-11eb-90ab-2495db8d85d3.png)
This screencopy of the log file you sent shows that the email has been integrated by the cron user, and not by the super-admin has it should be if you want to debug the filters, like explained [here](https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters)
Thank you
Regards,
Tomolimo

**Comment by victoria1984** [comment]
Hi, 
i sent you log file again. 
I've used super-admin profile, and i've runed the mailgate manually from the 'automatic actions' but the filter didn't work
[TicketCleaner.log](https://github.com/tomolimo/ticketcleaner/files/5501151/TicketCleaner.log)
Thank's

**Comment by tomolimo** [comment]
Hello @victoria1984 
Please try with the following pattern:
`/(<p class="MsoNormal" style="line-height:80%">(.*)<\/p>)/`
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @victoria1984 
I close this issue as I got no news from last post.
Feel free to re-open if you want to post news.
Thank you
Regards,
Tomolimo
