### ISSUE TITLE
tab ticketcleaner filter

### ISSUE THREAD

**Issue by TetyaseDaWina** [tomolimo/ticketcleaner#2]
Why do you have put the tab ticketcleaner filter in the principal tab Configuration ?
It will be better if this tab was on the principal tab Plugins like for exemple FusionInventory ? ^^

Also, very nice work :+1:

**Comment by tomolimo** [comment]
Hello,
For 2 reasons:
1. the plugin Fields does the same: configuration is in the 'Setup' menu.
2. the configuration of TicketCleaner is really similar to Setup: you do it one time and you forget it.

regards,
Tomolimo

**Comment by TetyaseDaWina** [comment]
Ok. 
Only use FI so don't know about Fields.
Thank you for your feedback
