### ISSUE TITLE
Ticket Cleaner - LetSignIT signatures

### ISSUE THREAD

**Issue by YoannRou** [tomolimo/ticketcleaner#22]
Hello,

We use LetSign IT to automatically create signatures and advertising banner in our emails.
They are added to Outlook with an app or SMTP connector from a smartphone.
It's very userful but for ticket's collected by mail it took a lot of space for nothing.

So far I have managed to remove all of the text but not the images embedded in the signature or the ad banner. 
They are uploaded to LetSignIt's website and not integrated in the email, is that the reason?

I'm not very comfortable with RegEx and other encodings things.
Do you have a solution or any idea to help me?

Thanks a lot,

**Our config:**

> Debian 10
> Server Version: 10.3.22-MariaDB-0+deb10u1
> GLPI 9.4.5 
> Ticket Cleaner 2.5.3

**Comment by tomolimo** [comment]
Hello @YoannRou 

Could you post in English?
Could you also post your GLPI configuration?

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @YoannRou 

Could you try a first regex?
`@<a href="https://cloud\.letsignit\.com/.*</a>@`
This one should delete the images.
Could you post result?

And then I'll propose you another one to delete the disclaimer text.

Thank you
Regards,
Tomolimo

**Comment by YoannRou** [comment]
Thank you for your quick answer !
I tried the RegEx and it's better than evertything i tried but not perfect.
In the description a lot of things are deleted but in history images are still uploded.

![image](https://user-images.githubusercontent.com/82201237/114191727-06c46d80-994d-11eb-92ce-e3587ad3b7d4.png)

**Comment by tomolimo** [comment]
Hello @YoannRou 

In fact the pictures are not in the HTML part of the email, but they are attached files in the email, this implies that the ticket description filters cannot delete them.
But there is another way to delete pictures: you have to place them in the /plugins/ticketcleaner/pictures/ folder of the plugins. This folder must contain the pictures that you want to exclude: copy/paste them into the folder will exclude them on the fly. And if you need to delete the already pictures from the tickets, then there is a script to do that in: /plugins/ticketcleaner/ purgepictures.php.

Thank you,
Regards,
Tomolimo

**Comment by YoannRou** [comment]
Tomolimo,

Ok I will try this. Thanks again.
Do you have any idea wich RegEx I have to create to delete the rest of the text inside the HTML board and the board itself ?

Regards,

**Comment by tomolimo** [comment]
Hello @YoannRou 
I closed this issue as there is no news, but feel free to reopen if you need to post news.
Thank you,
Regards,
Tomolimo
