### ISSUE TITLE
GLPI 10

### ISSUE THREAD

**Issue by perlporter** [tomolimo/ticketcleaner#26]
Is it already possible to run the plugin in version 10?
Congratulations for the project

**Comment by tomolimo** [comment]
Hello 
A version for GLPI 10 is planned for current month (June 2023).
Thank you,
Regards,
Tomolimo

**Comment by ak47d** [comment]
Hello. We are looking forward to the release of the plugin version for GLPI 10
The plugin for version 9.5 was able to run in GLPI 10+ by disabling or adjusting version control. But how correct and will it work at all?

**Comment by tomolimo** [comment]
Hello
It has been released here: https://github.com/tomolimo/ticketcleaner/releases
Sorry for not advertising at the time of the release.
Thannk you,
Regards,
Tomolimo
