### ISSUE TITLE
Version 4.0 don't update on mysql 5.7

### ISSUE THREAD

**Issue by fgendorf** [tomolimo/ticketcleaner#28]
Hi, the follow SQL fail to run on mysql 5.7 in the hook script.

```sql
ALTER TABLE `glpi_plugin_ticketcleaner_filters`
                  ALTER `regex` DROP DEFAULT,
                  ALTER `replacement` DROP DEFAULT;
```
I saw that structure changed a little, but the problem reported by mysql is:

Erro SQL [1101] [42000]: BLOB, TEXT, GEOMETRY or JSON column 'regex' can't have a default value

commenting this session the update works.

**Comment by tomolimo** [comment]
Hello @fgendorf 
Could you detail the GLPI vesion, and PHP version too?
Thank you,
Regards,
Tomolimo

**Comment by fgendorf** [comment]
> Hello @fgendorf Could you detail the GLPI vesion, and PHP version too? Thank you, Regards, Tomolimo

Hello @tomolimo , my GLPI is 10.0.7 and PHP 8.1.18, I tested in a Mysql 8 and the query works, the problem is with mysql 5.7.36

Thank you for you work!

> Hello @fgendorf Could you detail the GLPI vesion, and PHP version too? Thank you, Regards, Tomolimo

**Comment by tomolimo** [comment]
Hello @fgendorf 
I can't succeed to reproduce this behaviour....
I close the issue, but feel free to reopen it if you have more information to give.
Thank you,
Regards,
Tomolimo
