### ISSUE TITLE
Suggestion about Encoding.

### ISSUE THREAD

**Issue by OscarLoayzaB** [tomolimo/ticketcleaner#3]
Hello,
The plugin is perfect and I find it useful .
However , I had to change a line of the file " hook.php " .

`$parm->input['content'] = htmlentities( $temp_content, ENT_QUOTES) ;`

by

`$parm->input['content'] = htmlentities( $temp_content, ENT_QUOTES, 'UTF-8') ;`

Because:
Characters transformed type ( ' , ¨, ñ, ... ) when creating a ticket.

This change could be included in the code .??

Thanks.

**Comment by tomolimo** [comment]
Thank you for your proposal, I'll do it quickly
