### ISSUE TITLE
How to enable debug mode?

### ISSUE THREAD

**Issue by Zoddo** [tomolimo/ticketcleaner#30]
Hello,

I have a specific filter that is causing issues when enabled (it is adding a lot of "rn" in the content).
I tried to use the debug feature [as explained in the wiki](https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters), but when I enable the GLPI's debug mode (from the top right menu) and update a followup, the `/files/_log/TicketCleaner.log` file is not created. The webserver has permission to write there, and I even manually created the file (and set proper ownership) without success. Am I missing something?

I'm using GLPI 10.0.7 with Ticket Cleaner 4.0.0.

----
Just in case, the filter that is causing issues is:
```regex
%(?<=["\s])color:\s*(?:#005179|rgb\(0, 81, 121\)|#1f497d|rgb\(31, 73, 125\));?%i
```
with an empty replacement. It is working properly on regex101.com in PCRE2 mode.

Thanks!

**Comment by tomolimo** [comment]
Hello @Zoddo 
Did you look into the php error file?
Is there any error message in that file?
Thank you,
Regards,
Tomolimo

**Comment by Zoddo** [comment]
Yes, the php-errors.log file contains a few errors, but they are all related to ldap; nothing related to this plugin.

I've also checked the error log of the web server, but it contains nothing recent.

**Comment by tomolimo** [comment]
Hello @Zoddo 
That's really strange that log file is not created...
I'm going to check that, and I'll keep you informed.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @Zoddo,
I checked on my installation, GLPI 10.0.7, TicketCleaner 4.0.0 and I got the TicketClearner.log in the /files/_log folder...
I've two questions:
1. Did you activated the files for the logs, like shown below?
![image](https://github.com/tomolimo/ticketcleaner/assets/7569958/1511c374-f627-41fa-9f65-087152374cb0)
2. could you check that the _log folder is really where you think it is? For this look within the same GLPI page than above, there is a line where it shows: 
![image](https://github.com/tomolimo/ticketcleaner/assets/7569958/66908575-4a92-40db-be75-092620799cb2)

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @Zoddo 
I closed this issue as there is no news, but feel free to reopen if you need to post news.
Thank you,
Regards,
Tomolimo
