### ISSUE TITLE
Regex get interpreted and destroys pagelayout

### ISSUE THREAD

**Issue by blippercop** [tomolimo/ticketcleaner#31]
v4.0.0

Go to /ticketcleaner/front/filter.php
Add the column "regex" to the view

Create a new filter with
```
/<p style="color:red">HELLO!</p>/
```
or
```
/<td style=".+?#C1C1C1 .+?#C1C1C1 1.0pt; border-right:.+?>.+?Something<\/td>/
```
or
```
/(<br>){2,}/
```
go to /plugins/ticketcleaner/front/filter.php

See that the page is not the usual layout as the regex gets interpreted and the column give a wrong preview.

**Comment by tomolimo** [comment]
Hello @blippercop 
Did you try the debug mode to get the real content text on which the regex will be applied (to try to find a workaround)?
It could be that the current regex is not the good one for what you want...
Thank you,
Regards,
Tomolimo

**Comment by blippercop** [comment]
I don’t understand what you mean. The regex is working fine. Have you tested the steps to see what I mean?Am 18.10.2023 um 07:38 schrieb tomolimo ***@***.***>:﻿
Hello @blippercop
Did you try the debug mode to get the real content text on which the regex will be applied?
It could be that the current regex is not the good one for what you want...
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
ok, thank you for your answer.
