### ISSUE TITLE
plugin_version_ticketcleaner-10.0-bugfixes method must be defined! in /var/www/glpi/src/Plugin.php at line 1810

### ISSUE THREAD

**Issue by zgbyte** [tomolimo/ticketcleaner#37]
Hello,

Recently, I found this plugin to format my tickets.

But I get the following error when I copy the plugin to the /plugins folder.

After I enabled debug mode on top of the screen, I got a red alert: "PHP User Warning (512): plugin_version_ticketcleaner-10.0-bugfixes method must be defined! in /var/www/glpi/src/Plugin.php at line 1810."

![image](https://github.com/tomolimo/ticketcleaner/assets/43003029/ccdd03ce-8b46-40fe-ae95-3b4106cdebdd)

Am I doing something wrong or not?

Information about the system:
GLPI 10.0.15
PHP 8.1.2-1

Thanks.

**Comment by tomolimo** [comment]
Hello @zgbyte 
From where did you download the TicketCleaner plugin?
Was it from here https://github.com/tomolimo/ticketcleaner/releases/tag/4.0.3 ?
Or did you clone the repository?
Did you change the folder name from ticketcleaner to ticketcleaner-10.0-bugfixes?
Thank you,
Regards,
Tomolimo

**Comment by zgbyte** [comment]
Hello @tomolimo 

Sorry for late respond, i downloaded plugin from this link:

https://github.com/tomolimo/ticketcleaner/releases/tag/3.0.0

But i found that version is not working with GLPI 10, after downloading latest version plugin working normally.

Thank you for respond, and sorry once for "false" reporting.
