### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by Smiley-k** [tomolimo/ticketcleaner#5]
Hi, more examples ? I have a complete deletion of the description! I'm using the latest version. Thank you.

**Comment by tomolimo** [comment]
hello,
you may find help with this: https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters
regards,
Tomolimo

**Comment by Smiley-k** [comment]
Yes I tried, but alas not working.

I have here an example

i use **/[a-z ]+\Best Regards.*?you\./ui**

but then deleted all description.

```
Best Regards,


 
This email is intended only for the person to whom it is addressed and/or otherwise authorized personnel. The information contained herein and attached is confidential and the property of "COMPANY". If you are not the intended recipient, please be advised that viewing this message and any attachments, as well as copying, forwarding, printing, and disseminating any information related to this email is prohibited, and that you should not take any action based on the content of this email and/or its attachments. If you received this message in error, please contact the sender and destroy all copies of this email and any attachment. Please note that the views and opinions expressed herein are solely those of the author and do not necessarily reflect those of the company. While antivirus protection tools have been employed, you should check this email and attachments for the presence of viruses. No warranties or assurances are made in relation to the safety and content of this email and attachments. "COMPANY" accepts no liability for any damage caused by any virus transmitted by or contained in this email and attachments. No liability is accepted for any consequences arising from this email. 

Information, software, products and services published on this email may include inaccuracies or typographical errors. In no event shall "COMPANY" and/or its employees be liable for any direct, indirect, punitive, incidental, special or consequential damages arising out of, or in any way connected with, the use of this email or for any information, products and/or services obtained herein, whether based on contract, tort, strict liability or otherwise, even if "COMPANY" has been advised of the possibility of damages. Because some jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages, the above limitation may not apply to you. 
```

**Comment by Smiley-k** [comment]
I may have figured out how it works. but I would like more examples. Here for example how to delete a picture ? if I know sh1 **179ecce84bbefa43bf990a6473473cbe5cf8cd3d**

**Comment by tomolimo** [comment]
Hello, 
Normaly you just have to save the picture into the dedicated folder 'pictures' in the plug-in folder. Check the wiki. 
Regards 
Tomolimo

**Comment by Smiley-k** [comment]
Yes, of course I copied the picture from
/glpi/files/_tmp#
in
glpi/plugins/ticketcleaner/pictures#

but it is not working, maybe more?

**Comment by tomolimo** [comment]
I think there is a bug I'll look at it tomorrow. 
Tomolimo

**Comment by tomolimo** [comment]
hello,
could you give me back info about your configuration?
Thank you
Tomolimo

**Comment by Smiley-k** [comment]
Hi, Yes found the problem why the description was removed. At the end of the recording was blank. 
**/[a-z ]+Best Regards.*?you\./ui**
(sorry for this concern), but the picture is not removed from the signature.

The picture I copied from the folder
/glpi/files/_tmp#
in
glpi/plugins/ticketcleaner/pictures#

what am I doing wrong ?

**Comment by tomolimo** [comment]
hello,
could you give me back info about your GLPi configuration?
Thank you
Tomolimo

**Comment by Smiley-k** [comment]
Yes, of course.
ubuntu 14.04
**GLPI 9.1.1**
Could be something else, say.

**Comment by tomolimo** [comment]
and versions of installed plugins?

**Comment by Smiley-k** [comment]
Forgot to specify version.

**Ticket Cleaner	2.0.4**

**Comment by tomolimo** [comment]
Did you look into the log file TicketCleaner.log?

**Comment by Smiley-k** [comment]
```
2016-11-28 15:29:58 [2@rp-vsr-03]
Ticket: 'test'
        File: '/var/www/glpi/files/_tmp/image001.png'   type: 'image/png'       sha1: '179ecce84bbefa43bf990a6473473cbe5cf8cd3d'        deleted: 'False'
2016-11-28 16:59:09 [2@rp-vsr-03]
Ticket: 'test'
        File: '/var/www/glpi/files/_tmp/image001.png'   type: 'image/png'       sha1: '179ecce84bbefa43bf990a6473473cbe5cf8cd3d'        deleted: 'False'
2016-11-29 09:37:49 [2@rp-vsr-03]
Ticket: 'Удаление подписи'
        File: '/var/www/glpi/files/_tmp/image001.png'   type: 'image/png'       sha1: '179ecce84bbefa43bf990a6473473cbe5cf8cd3d'        deleted: 'False'
2016-11-29 09:39:11 [2@rp-vsr-03]
Ticket: 'Test'
        File: '/var/www/glpi/files/_tmp/image001.png'   type: 'image/png'       sha1: '179ecce84bbefa43bf990a6473473cbe5cf8cd3d'        deleted: 'False'
2016-11-29 09:45:03 [@rp-vsr-03]
Ticket: 'Test'
        File: '/var/www/glpi/files/_tmp/image001.png'   type: 'image/png'       sha1: '179ecce84bbefa43bf990a6473473cbe5cf8cd3d'        deleted: 'False'

```

**Comment by tomolimo** [comment]
as a workaround, you may insert into the DB table the sha1 of the picture.
the table is `glpi_plugin_ticketcleaner_picturehashes`

**Comment by tomolimo** [comment]
but to investigate further the issue: could you tell me the name of the web client that is used to send the emails?

**Comment by Smiley-k** [comment]
I send messages via outlook

our database has information about the picture

![image](https://cloud.githubusercontent.com/assets/11009787/20702729/25a900b8-b62a-11e6-8a55-c3c1085958e9.png)

**Comment by Smiley-k** [comment]
But these notes are on the test server, production server installed **fusioninventory** and I don't see glpi_plugins and glpi_plugin_ticketcleaner_picturehashes

**Comment by tomolimo** [comment]
which outlook version? and which msexchange version?
I have same troubles with our new exchange server.

Regarding the table content, you can see that the sha1 are not matching the one that are received by the mail receiver. The mail receiver receives `179ecce84bbefa43bf990a6473473cbe5cf8cd3d` and the picture files generate another sha1. I suspect that msexchange newest release is doing some conversion (compression?) on embedded picture in emails.

so if you add a new record (or update existing one) with the sha1 from the TicketCleaner.log, then the embedded picture will be really deleted from the ticket.

**Comment by Smiley-k** [comment]
Yes, I use MS Exchange 2010. I'll try to do as you recommend.

outlook 2010

**Comment by Smiley-k** [comment]
Yes you are right, a solution to the problem when working with MS Exchange server.

Thank you very much.

but how to proceed with this in the future ?

**Comment by tomolimo** [comment]
It's seems to be an issue with outlook:
see this: http://superuser.com/questions/211020/prevent-outlook-2010-insert-picture-resizing-image
and this: https://www.howto-outlook.com/faq/unsharpimages.htm

**Comment by tomolimo** [comment]
this one is also very interesting: https://www.msoutlook.info/question/545
the conclusion is: if you change the way the 'wrap text' is done for the embedded picture, then it will change the compression of the picture...

**Comment by tomolimo** [comment]
As an example:
![image](https://cloud.githubusercontent.com/assets/7569958/20706719/e42c335e-b628-11e6-8b88-a86983a03a43.png)
On the left is the embedded picture sent with my outlook (before sending of course), and on the right is the picture that GLPi received, you can see that Outlook has re-sampled and resized the initial picture, and such the DB stored sha1 can't matched the one received...

**Comment by Smiley-k** [comment]
okay, thank you.

**Comment by tomolimo** [comment]
linked to #9
