### ISSUE TITLE
pictures and text to remove

### ISSUE THREAD

**Issue by satyan01** [tomolimo/ticketcleaner#6]
Hello

I would like to know where can I find the picture to copy in pictures folder to exclude them from the ticket.

It is in the signature but I can't find in glpi folder where pictures are stored until the ticket is created from receiver

**Comment by satyan01** [comment]
Could you help me for the code regex to remove signature please

 

  	Alexander Stoen
IT Operations Administrator
Information Technology	Unigestion (UK) Ltd
4 Stratford Place
London W1C 1AT
United Kingdom
  	Dir.  +44 (0) 207 529 5218	Tel.  +44 (0) 207 529 5200
  	Fax. +44 (0) 207 529 5230	Fax. +44 (0) 207 529 6389
  	astoen@unigestion.com
www.unigestion.com

  	  
  	   Follow Unigestion on LinkedIn.

  	  
  	 

  	Unigestion (UK) Limited is authorised and regulated by the Financial Conduct Authority. Registered in England and Wales No 3886428.

**Comment by tomolimo** [comment]
for filter: uses this https://github.com/tomolimo/ticketcleaner/wiki/Debug-filters

**Comment by tomolimo** [comment]
Hello Satyan01,
Sorry for my late answer, but I've been very busy upgrading our own GLPI installation.

In order to correctly helping you, I need the debug output from the log file I previously showed you the link.

Thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
I close this issue as there is no info from @satyan01 
Feel free to re-open with new information.
