### ISSUE TITLE
Compatibility with GLPI 9.2.2

### ISSUE THREAD

**Issue by FRANCOIS50** [tomolimo/ticketcleaner#8]
Hi do you have a idea wenn you will adapte this plugin to the new glpi version 9.2.2

Thanks in advance for your feed-back

**Comment by tomolimo** [comment]
Hello,
I think around June 2018,
regards,
Tomolimo

**Comment by lolokai** [comment]
Hello,
Can you say me if this plugin is now compatible with GLPI 9.2 and 9.3 ?

**Comment by tomolimo** [comment]
Probably during summer 2018

**Comment by tomolimo** [comment]
Partially fixed by last commit https://github.com/tomolimo/ticketcleaner/commit/49667483760c513fe390c957b03e275e1eb76810 (compatibility with 9.2)
For 9.3 compatibility: it is planned but for end of Autumn 2018
Thank you
regards,
Tomolimo

**Comment by juveboss** [comment]
Hello Tomolimo.

Is it compatible with versions 9.2 and 9.3?

My regex does not work anymore since my migration from Glpi 9.1 to 9.2, I tried on 9.3 it does not work too ...

**Comment by tomolimo** [comment]
Hello @juveboss 
I've a beta version for 9.2
I'll release it next week.
Regards,
Tomolimo

**Comment by juveboss** [comment]
Hello @tomolimo 

The release is available ? 

Best regards

**Comment by tomolimo** [comment]
Hello @juveboss 
I've currently a bug in it, and can't release it like that. I'm working on it, and keep you inform as soon as it will be available.
Thank you
Regards,
Tomolimo
